version: '3.5'
services:
  doc:
    build: ./doc/
    ports:
      - 8080:8080
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      URLS: "[
        { url: '/doc/server.yml', name: 'Server' }
        ]"
    networks:
      - app
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    networks:
      - app
  pgadmin:
    image: dpage/pgadmin4:7.8
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    networks:
      - app
    depends_on:
      - postgres
  server:
    build: .
    ports:
      - 8800:8800
    volumes:
      - ./:/app
    networks:
      - app

networks:
  app:
    driver: bridge
