openapi: 3.0.1
info:
  title: Fastify Project
  description: The simple fastify project
  version: 1.0.0
servers:
- url: http://localhost:8080
security:
- jwt: []
tags:
  - name: Auth
paths:
  /v1/auth/register:
    post: 
      tags:
      - Auth
      summary: Register
      description: register a user 
      operationId: register
      requestBody: 
        description: create user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        201:
          description: Successful operation
          content: {}
        401:
          description: Missing authentication
          content: {}
        500:
          description: Internal server error
          content: {}

components:
  schemas:
    register: 
      required:
      - fullName
      - username
      - password
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        password:
          type: string
  securitySchemes:
    jwt:
      type: apiKey
      description: 'Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".  #'
      name: Authorization
      in: header